In [15]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [16]:
w = torch.tensor(2.,requires_grad=True)
x=torch.tensor(1.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)

In [17]:
y = w*x+b
y.backward()

In [18]:
x.grad

tensor(2.)

In [19]:
w.grad

tensor(1.)

In [20]:
b.grad

tensor(1.)

In [30]:
x = torch.randn(2,3)

In [31]:
x

tensor([[ 0.0826, -1.1262,  0.3033],
        [ 0.4233,  0.3524,  0.4723]])

In [42]:
y = torch.randn(2,2)

In [43]:
y


tensor([[ 0.6396,  0.0526],
        [-0.7943, -1.3776]])

In [44]:
linear = nn.Linear(3,2)

In [45]:
linear.weight

Parameter containing:
tensor([[ 0.4993,  0.1383, -0.5475],
        [ 0.4759,  0.0690, -0.0983]], requires_grad=True)

In [46]:
linear.bias

Parameter containing:
tensor([0.4927, 0.5505], requires_grad=True)

In [47]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(),lr=0.01)

In [48]:
pred=linear(x)

In [49]:
pred

tensor([[0.2121, 0.4822],
        [0.4942, 0.7298]], grad_fn=<AddmmBackward0>)

In [50]:
loss=criterion(pred,y)

In [51]:
loss

tensor(1.6172, grad_fn=<MseLossBackward0>)

In [52]:
#计算梯度
loss.backward()

In [53]:
linear.weight.grad

tensor([[0.2550, 0.4678, 0.2395],
        [0.4638, 0.1294, 0.5629]])

In [54]:
linear.bias.grad

tensor([0.4305, 1.2685])

In [55]:
# 反向传播
optimizer.step()

In [56]:
pred = linear(x)

In [57]:
pred

tensor([[0.2121, 0.4689],
        [0.4860, 0.7121]], grad_fn=<AddmmBackward0>)

In [59]:
loss=criterion(pred,y)
loss

tensor(1.5905, grad_fn=<MseLossBackward0>)

In [61]:
for i in range(10):
    pred=linear(x)
    loss=criterion(pred,y)
    print(f'loss:{loss}\n')
    loss.backward()
    optimizer.step()

loss:1.5381572246551514

loss:1.4624302387237549

loss:1.3663852214813232

loss:1.2539328336715698

loss:1.129592776298523

loss:0.9982776641845703

loss:0.8650593757629395

loss:0.7349335551261902

loss:0.6125896573066711

loss:0.5022032856941223



In [64]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [66]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [67]:
y = torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [69]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

# Input pipeline

In [70]:
# transform为对数据集的数据进行的操作，甚至可以实现一个操作序列
'''
transform = transforms.Compose([ 
    transforms.RandomHorizontalFlip(),  # 随机水平翻转
    transforms.RandomRotation(10),      # 随机旋转
    transforms.ToTensor()               # 转换为张量并归一化])
'''
train_dataset = torchvision.datasets.CIFAR10(root='./data',
                                             train=True,
                                             transform=transforms.ToTensor(),
                                             download=True
                                            )

100%|████████████████████████████████████████████| 170498071/170498071 [00:11<00:00, 14472792.88it/s]


Extracting ./data\cifar-10-python.tar.gz to ./data


In [72]:
train_dataset

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [73]:
# 得到的是数组，每一个元素是一个数据
train_dataset[0]

(tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],
 
         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],
 
         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ...,

In [75]:
train_dataset[2]

(tensor([[[1.0000, 0.9922, 0.9922,  ..., 0.9922, 0.9922, 0.9922],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
          ...,
          [0.4431, 0.4353, 0.4118,  ..., 0.2824, 0.2824, 0.2824],
          [0.4353, 0.4078, 0.3882,  ..., 0.2667, 0.2745, 0.3059],
          [0.4157, 0.3882, 0.3725,  ..., 0.3059, 0.3098, 0.3137]],
 
         [[1.0000, 0.9922, 0.9922,  ..., 0.9922, 0.9922, 0.9922],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 0.9961, 0.9961,  ..., 0.9961, 0.9961, 0.9961],
          ...,
          [0.4706, 0.4627, 0.4392,  ..., 0.3176, 0.3137, 0.3137],
          [0.4627, 0.4353, 0.4157,  ..., 0.2941, 0.2980, 0.3294],
          [0.4431, 0.4157, 0.4000,  ..., 0.3333, 0.3333, 0.3373]],
 
         [[1.0000, 0.9922, 0.9922,  ..., 0.9922, 0.9922, 0.9922],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 0.9961, 0.9961,  ...,

In [71]:
image,label=train_dataset[0]

In [76]:
image

tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
         [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
         [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
         ...,
         [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
         [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
         [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

        [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
         [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
         [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
         ...,
         [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
         [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
         [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

        [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
         [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
         [0.0824, 0.0000, 0.0314,  ..., 0.1961, 0.1961, 0.

In [77]:
label

6

In [78]:
image.size()

torch.Size([3, 32, 32])

In [80]:
len(train_dataset)

50000

In [81]:
type(train_dataset)

torchvision.datasets.cifar.CIFAR10

In [84]:
# 64个数据为1组
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                     batch_size=64,
                                     shuffle=True)

In [85]:
train_loader

In [87]:
len(train_loader)

782

In [88]:
data_iter = iter(train_loader)

In [89]:
data_iter

In [90]:
images,labels=data_iter.next()

AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

In [98]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        self.dataset = torchvision.datasets.MNIST(root="./MNIST",
                                                  train=True,
                                                  download=True,
                                                transform=transforms.ToTensor()
                                                 )
        self.DataLoader = torch.utils.data.DataLoader(dataset=self.dataset,
                                                      shuffle=True,
                                                      batch_size=32)
    def __getitem__(self,index):
        print(self.dataset[index])
        image,label = self.dataset[index]
        print(image,label)
    
    def __len__(self):
        return len(self.dataset)

In [99]:
myDataSet = CustomDataset()

In [100]:
myDataSet.__getitem__(1)

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000

In [101]:
myDataSet.__len__()

60000

## pretrained model

In [102]:
resnet = torchvision.models.resnet18(pretrained=True)

D:\Python3.10.4\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\Python3.10.4\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\Dreamer/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|███████████████████████████████████████████████████████████| 44.7M/44.7M [00:16<00:00, 2.86MB/s]


In [103]:
# 微调
for param in resnet.parameters():
    param.requires_grad=False

resnet.fc=nn.Linear(resnet.fc.in_features,100)

In [104]:
image = torch.randn(64,3,224,224)

In [106]:
output = resnet(image)

In [107]:
output.size()

torch.Size([64, 100])

Save and load the entire model

In [108]:
# Save and load the entire model.
torch.save(resnet,'model.ckpt')

In [109]:
model = torch.load('model.ckpt')

C:\Users\Dreamer\AppData\Local\Temp\ipykernel_17108\240101920.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('model.ckpt')


In [110]:
# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

C:\Users\Dreamer\AppData\Local\Temp\ipykernel_17108\250726142.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  resnet.load_state_dict(torch.load('params.ckpt'))


<All keys matched successfully>