In [1]:
import numpy as np
from numpy import random

## numpy


np.mat()生成的始终为二维数组matrix类型

In [2]:
np.mat([1,2])

matrix([[1, 2]])

In [3]:
np.mat([[1,2],[2,3]])

matrix([[1, 2],
        [2, 3]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
a = np.eye(3)

In [6]:
b = a+np.eye(3)

In [7]:
a.dot(b.T)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [8]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

.dot()可以实现矩阵的乘法，矩阵与向量的乘法以及向量与向量的乘法

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [10]:
A

array([[1, 2],
       [3, 4]])

In [11]:
B

array([[5, 6],
       [7, 8]])

In [12]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [13]:
c = np.array([1,2])

In [14]:
A@(c)

array([ 5, 11])

np.hstack([A,B]):将两个矩阵相对应的行拼接起来

In [15]:
np.hstack([A,B])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
random.randn(2,2)

array([[ 0.62890212,  0.16297074],
       [-0.97233025, -1.20435029]])

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


np.max：返回最大值，不指定axis时，代表返回矩阵中最大的值
指定axis后，=0表示计算每列最大的值，=1表示返回每行最大的值

In [19]:
np.max(arr,axis=1)

array([3, 6, 9])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])