In [2]:
import torch

In [3]:
a = torch.tensor([1,2,3],dtype = int)


In [4]:
a


tensor([1, 2, 3])

In [5]:
a.dtype

torch.int64

In [7]:
b= torch.tensor([4,5,6],dtype = float)

In [8]:
b


tensor([4., 5., 6.], dtype=torch.float64)

In [9]:
c = torch.tensor([[1,2,3],
                 [4,5,6]])

In [10]:
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#数据的维度
c.ndim

2

In [15]:
c.size()
c.shape

torch.Size([2, 3])

In [16]:
y = torch.randn(2,3)

In [17]:
y

tensor([[-0.8912, -1.2025, -0.1412],
        [ 1.1907,  0.9337, -0.2319]])

In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [23]:
device

device(type='cpu')

In [25]:
torch.cuda.current_device()

AssertionError: Torch not compiled with CUDA enabled

In [21]:
z = torch.randn(2,3,device = device)

In [22]:
z

tensor([[ 0.7157, -1.4626,  1.5819],
        [-1.4399,  0.4905,  0.0448]])

In [26]:
import sys

In [27]:
sys.version

'3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]'